app:
  title: Devportal
  baseUrl: http://localhost:3000
permission:
  enabled: false
auth:
  environment: development
backend:
  auth:
    keys:
      - secret: secret
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  database:
    client: better-sqlite3
    connection: ':memory:'
  cache:
    store: memory
  cors:
    origin: http://localhost:3000 #http://localhost:3000
    methods: [GET, POST, PUT, DELETE, PATCH]
    credentials: true
organization:
  name: Devportal
platform:
  behaviour: 
    mode: demo #product, demo, workshop, anything else  - get config directly from here
    home: true
    catalog: true
    apis: false
    resources: false
    create: true
    docs: false
    groups: false
    apiManagement: false
  guest:
    enabled: true
  defaultGroup:
    enabled: true
  group:
    admin: admin
    user: user
  apiManagement:
    enabled: false
    readOnlyMode: false #boolean
enabledPlugins:
  gitlabPlugin: false
  keycloak: false
  infracost: false
  azureDevops: false
  grafana: false
  kubernetes: false
  vault: false
vault:
  enabled: false
  domain: null
grafana:
  enabled: false
  domain: null
argocd:
  enabled: false
keycloak:
  enabled: false
azureDevops:
  enabled: false
infracost:
  enabled: false

search:
  pg:
    highlightOptions:
      useHighlight: true # Used to enable to disable the highlight feature. The default value is true
      maxWord: 35 # Used to set the longest headlines to output. The default value is 35.
      minWord: 15 # Used to set the shortest headlines to output. The default value is 15.
      shortWord: 3 # Words of this length or less will be dropped at the start and end of a headline, unless they are query terms. The default value of three (3) eliminates common English articles.
      highlightAll: false # If true the whole document will be used as the headline, ignoring the preceding three parameters. The default is false.
      maxFragments: 0 # Maximum number of text fragments to display. The default value of zero selects a non-fragment-based headline generation method. A value greater than zero selects fragment-based headline generation (see the linked documentation above for more details).
      fragmentDelimiter: ' ... ' 
    schedule:        
      frequency: 
        minutes: 3
      timeout: 
        minutes: 5
techdocs:
  builder: "local" # Alternatives - 'external'
  generator:
    runIn: "local"
  publisher:
    type: "local" # Alternatives - 'googleGcs' or 'awsS3' or 'azureBlobStorage' or 'openStackSwift'. Read documentation for using alternatives.
