apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.componentId | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{ values.repoUrl }}
    github.com/workflows: terraform.yml,destroy.yml
spec:
  type: devops
  lifecycle: development
  owner: ${{ values.owner }}